### ISSUE TITLE
Permitir o reinício automático da geração de XML por falha na conectividade com o banco de dados

### ISSUE THREAD

**Issue by wilercoelho** [felipegiotto/justica_em_numeros_2016#35]
Durante o processo de geração de remessas maiores, existe a possibilidade do banco de consulta utilizado ficar indisponível por algumas horas para sincronização com o banco de produção.

Como esse processo acontece geralmente no final do dia ou de madrugada, será perdido todo o processamento após a conclusão da sincronização, por isso seria interessante fazer um tratamento mais adequado desse tipo de exceção para permitir que o processo reinicie após o banco ficar disponível novamente.

Na implementação atual uma exceção é lançada e o processo é interrompido, tendo que ser reiniciado manualmente.

**Comment by wilercoelho** [comment]
Segue o exemplo de erro:

2020-11-24T22:50:47,712 ERROR Exception in thread "main" 
2020-11-24T22:50:47,712 ERROR org.postgresql.util.PSQLException: This connection has been closed.
2020-11-24T22:50:47,712 ERROR 	at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:820)
2020-11-24T22:50:47,712 ERROR 	at org.postgresql.jdbc4.AbstractJdbc4Connection.createArrayOf(AbstractJdbc4Connection.java:90)
2020-11-24T22:50:47,713 ERROR 	at org.postgresql.jdbc4.Jdbc4Connection.createArrayOf(Jdbc4Connection.java:21)
2020-11-24T22:50:47,713 ERROR 	at br.jus.trt4.justica_em_numeros_2016.tasks.Op_2_GeraXMLsIndividuais.prepararCacheDadosProcessos(Op_2_GeraXMLsIndividuais.java:582)
2020-11-24T22:50:47,713 ERROR 	at br.jus.trt4.justica_em_numeros_2016.tasks.Op_2_GeraXMLsIndividuais.gerarXML(Op_2_GeraXMLsIndividuais.java:395)
2020-11-24T22:50:47,713 ERROR 	at br.jus.trt4.justica_em_numeros_2016.tasks.Op_2_GeraXMLsIndividuais.gerarXMLs(Op_2_GeraXMLsIndividuais.java:305)
2020-11-24T22:50:47,713 ERROR 	at br.jus.trt4.justica_em_numeros_2016.tasks.Op_2_GeraXMLsIndividuais.executarOperacaoGeracaoXML(Op_2_GeraXMLsIndividuais.java:250)
2020-11-24T22:50:47,713 ERROR 	at br.jus.trt4.justica_em_numeros_2016.tasks.Op_2_GeraXMLsIndividuais.main(Op_2_GeraXMLsIndividuais.java:176)

A instrução onde o erro acontece é:
Array arrayNumerosProcessos = conexaoBasePrincipal.createArrayOf("varchar", numerosProcessos.toArray());

**Comment by wilercoelho** [comment]
https://gitlab.trt15.jus.br/estatistica_cnj_jt/datajud-extrator/-/issues/13
